-- CREATE DATABASE iglesia_php;
USE iglesia_php;

CREATE TABLE members(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(30) NOT NULL,
    apellido_paterno VARCHAR(30) NOT NULL,
    apellido_materno VARCHAR(30) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    estado_civil VARCHAR(30) NOT NULL,
    sexo VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    numero_celular VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE baptisms(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    member_id INT(11) UNSIGNED NOT NULL,
    pastor_id INT(11) UNSIGNED NOT NULL,
    fecha_bautizo DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (pastor_id) REFERENCES members(id) ON DELETE CASCADE ON UPDATE CASCADE
);